spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        jdbc:
          lob:
            non_contextual_creation: true
        default_batch_fetch_size: 50
  transaction:
    default-timeout: 30s
    rollback-on-commit-failure: true
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

logging:
  level:
    liquibase: DEBUG